[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    e2e: End-to-End tests
    unit: Unit tests
    integration: Integration tests
    slow: Slow running tests

# Async settings
asyncio_mode = auto

# Coverage settings
[coverage:run]
source = app
omit = 
    */tests/*
    */migrations/*
    */__pycache__/*
