"""Add webhook idempotency and portal url to subscriptions

Revision ID: 6153f96ac3a5
Revises: 73c9cb404cb9
Create Date: 2025-12-21 16:54:57.206172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6153f96ac3a5'
down_revision: Union[str, None] = '73c9cb404cb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_messages_topic_id', table_name='chat_messages')
    op.drop_index('ix_chat_messages_user_id', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_constraint('push_subscriptions_endpoint_key', 'push_subscriptions', type_='unique')
    op.create_unique_constraint(op.f('uq_push_subscriptions_endpoint'), 'push_subscriptions', ['endpoint'])
    op.drop_index('ix_quiz_results_completed_at', table_name='quiz_results')
    op.drop_index('ix_quiz_results_topic_id', table_name='quiz_results')
    op.drop_index('ix_quiz_results_user_id', table_name='quiz_results')
    op.add_column('subscriptions', sa.Column('customer_portal_url', sa.String(length=512), nullable=True))
    op.add_column('subscriptions', sa.Column('last_webhook_event_id', sa.String(length=255), nullable=True))
    op.drop_index('ix_topics_content_blocknote', table_name='topics', postgresql_using='gin')
    op.drop_column('users', 'use_new_dashboard')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('use_new_dashboard', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index('ix_topics_content_blocknote', 'topics', ['content_blocknote'], unique=False, postgresql_using='gin')
    op.drop_column('subscriptions', 'last_webhook_event_id')
    op.drop_column('subscriptions', 'customer_portal_url')
    op.create_index('ix_quiz_results_user_id', 'quiz_results', ['user_id'], unique=False)
    op.create_index('ix_quiz_results_topic_id', 'quiz_results', ['topic_id'], unique=False)
    op.create_index('ix_quiz_results_completed_at', 'quiz_results', ['completed_at'], unique=False)
    op.drop_constraint(op.f('uq_push_subscriptions_endpoint'), 'push_subscriptions', type_='unique')
    op.create_unique_constraint('push_subscriptions_endpoint_key', 'push_subscriptions', ['endpoint'])
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('topic_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tool_calls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name='chat_messages_topic_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='chat_messages_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chat_messages_pkey')
    )
    op.create_index('ix_chat_messages_user_id', 'chat_messages', ['user_id'], unique=False)
    op.create_index('ix_chat_messages_topic_id', 'chat_messages', ['topic_id'], unique=False)
    # ### end Alembic commands ###
